apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-twitter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-twitter
  template:
    metadata:
      labels:
        app: ml-twitter
    spec:
      containers:
      - name: ml-twitter
        image: nutka/lucasaguiar-ml_twitter:0.3
        ports:
        - containerPort: 5000
